# Generated by Django 4.2.6 on 2023-10-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('battery_mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Charging Date')),
                ('charge', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ev')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
